// IMPORTANT! This file is autogenerated by the `type-safe-next-routes`
// package. You should _not_ update these types manually...

declare module 'next-type-safe-routes' {
  type Query = { [key: string]: any }
  export type TypeSafePage =
    | '/'
    | { route: '/'; query?: Query }
    | {
        route: '/sketches/[sketch]'
        params: { sketch: string | number }
        query?: Query
      }
    | '/sketches'
    | { route: '/sketches'; query?: Query }
    | '/ui'
    | { route: '/ui'; query?: Query }
    | {
        route: '/writing/[slug]'
        params: { slug: string | number }
        query?: Query
      }
    | '/writing'
    | { route: '/writing'; query?: Query }
  export type TypeSafeApiRoute =
    | '/api/generative-api'
    | { route: '/api/generative-api'; query?: Query }
    | '/api/generative-waves'
    | { route: '/api/generative-waves'; query?: Query }
  export const getPathname: (
    typeSafeUrl: TypeSafePage | TypeSafeApiRoute
  ) => string
  export const getRoute: (
    typeSafeUrl: TypeSafePage | TypeSafeApiRoute
  ) => string
}
